name: Build Python APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # This Action installs the Android SDK and compiles Python
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action-2@v1
        with:
          command: buildozer android debug
          buildozer_version: master

      # Upload the result
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Savings-App-Python
          path: bin/*.apk
